version: '3.7'

services:
  dummy:
    image: alpine
    command: sleep 200
    init: true
  x:
    image: alpine
    restart: on-failure
    command: sh -c 'echo starting && sleep 200'
    init: true
    volumes:
      # - ./:/src
      - ./setup.py:/src/setup.py








